zajazd_website/gallery/urls.py
from django.conf.urls import url
from .views import Albums, Gallery, PhotoView


app_name = 'gallery'

urlpatterns = [
    url(r'^$', Albums.as_view(), name='albums'),
    url(r'^(?P<album_id>(\d)+)/$', Gallery.as_view(), name='photos'),
    url(r'^photo/(?P<photo_id>(\d)+)', PhotoView.as_view(), name='photo')
]

zajazd_website/mainsite/urls.py
from django.conf.urls import url
from .views import Index, Contact, AboutUs


app_name = 'mainsite'

urlpatterns = [
    url(r'^$', Index.as_view(), name='main'),
    url(r'^about/$', AboutUs.as_view(), name='about'),
    url(r'^contact/$', Contact.as_view(), name='contact'),
]

zajazd_website/reservation/urls.py
from django.conf.urls import url
from .views import ReservationView, Pdf


app_name = 'reservation'

urlpatterns = [
    url(r'^$', ReservationView.as_view(), name='reservation'),
    url(r'^pdf_get/$', Pdf.as_view(), name='PDF'),
]

zajazd_website/zajazd_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mainsite.views import Index, AboutUs, Contact
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainsite.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^reservation/', include('reservation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zajazd_website/mainsite/models.py
from django.db import models


class About(models.Model):
    paragraph_title = models.CharField(max_length=64,
                                       blank=True,
                                       null=True,
                                       verbose_name='Tytuł akapitu')

    paragraph_content = models.TextField(blank=False,
                                         null=False,
                                         verbose_name='Zawartośc akapitu')

    class Meta:
        verbose_name = 'O Nas'
        verbose_name_plural = 'O nas'

    def __str__(self):
        if self.paragraph_title:
            return self.paragraph_title
        return self.paragraph_content[:32] + '...'

zajazd_website/mainsite/views.py
from django.views.generic import ListView
from django.shortcuts import render
from django.views import View

from .models import About


class Index(View):
    def get(self, request):
        return render(request, 'index/index.html')


class AboutUs(ListView):
    model = About
    template_name = 'index/about.html'
    context_object_name = 'abouts'


class Contact(View):
    def get(self, request):
        return render(request, 'index/contact.html')

zajazd_website/mainsite/templates/base.html
<!DOCTYPE html>
<html lang="pl">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Zajazd Myśliwski - Restauracja - Hotel - Catering">
    <meta name="author" content="Rafał Bielicki">

    <title>
        Zajazd Myśliwski
        {% block title%}
        {% endblock %}

    </title>

    {% load static %}

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Fornt Awesome  -->
    <script src="https://use.fontawesome.com/627ef9b005.js"></script>

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- Page custom CSS -->
    <link href="{% static 'css/zajazd.css' %}" rel="stylesheet" type="text/css">

    <!-- Page custom icons -->
    <link href="{% static 'css/zajazd-icons.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-custom" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-circle-o-notch"></i> Menu
                </button>
            <a class="navbar-brand" href="{% url 'mainsite:main' %}">
                <i class="zajazd-icon logo-white normal"></i> <span class="light">ZAJAZD MYŚLIWSKI</span>
            </a>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse"">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'mainsite:about' %}">O nas</a>
                    </li>
                    <li>
                        <a href="{% url 'mainsite:contact' %}">Kontakt</a>
                    </li>
                    <li>
                        <a href="{% url 'gallery:albums' %}">Galeria</a>
                    </li>
                    <li>
                        <a href="{% url 'reservation:reservation' %}">Rezerwacja</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->


                {% block content %}

                {% endblock %}

    <footer class="navbar-fixed-bottom">
        <a href="https://github.com/SadiXD">&nbsp;<i class="fa fa-github fa-3x"></i></a>
        &nbsp;
        <a href="https://www.linkedin.com/in/rafał-bielicki-008611141/"><i class="fa fa-linkedin fa-3x"></i></a>
        &nbsp;
        <a href="https://www.facebook.com/profile.php?id=100000461692322"><i class="fa fa-facebook-square fa-3x"></i></a>
    </footer>

    <!-- jQuery 3.2.1 -->
    <script   src="https://code.jquery.com/jquery-3.2.1.min.js"
              integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
              crossorigin="anonymous"></script>

    <!-- jQuery UI 1.12.1 -->
    <script   src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
              integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
              crossorigin="anonymous"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Datepicker date range validation -->
    <script src="{% static 'js/datepicker_valid.js' %}"></script>

    <!-- Custom Datepicker CSS -->
    <link rel="stylesheet" href="{% static 'css/zajazd-datepicker.min.css' %}">
</body>

</html>