zajazd_website/gallery/urls.py
from django.conf.urls import url
from .views import Albums, Gallery, PhotoView


app_name = 'gallery'

urlpatterns = [
    url(r'^$', Albums.as_view(), name='albums'),
    url(r'^(?P<album_id>(\d)+)/$', Gallery.as_view(), name='photos'),
    url(r'^photo/(?P<photo_id>(\d)+)', PhotoView.as_view(), name='photo')
]

zajazd_website/reservation/urls.py
from django.conf.urls import url
from .views import ReservationView, Pdf


app_name = 'reservation'

urlpatterns = [
    url(r'^$', ReservationView.as_view(), name='reservation'),
    url(r'^pdf_get/$', Pdf.as_view(), name='PDF'),
]

zajazd_website/zajazd_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mainsite.views import Index, AboutUs, Contact
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainsite.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^reservation/', include('reservation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zajazd_website/reservation/models.py
import os
from datetime import date
from django.db import models
from datetime import datetime
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A5
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from .query import RoomQuerySet
from django.dispatch import receiver
from django.core.mail import send_mail
from client.models import Client


class Room(models.Model):

    objects = RoomQuerySet.as_manager()

    room_number = models.PositiveIntegerField(unique=True,
                                              verbose_name='Nr. Pokoju')

    capacity = models.PositiveIntegerField(verbose_name='Maksymalna ilośc gości')

    lake_view = models.BooleanField(default=False,
                                    verbose_name='Widok na jezioro')

    class Meta:
        verbose_name = 'Pokój'
        verbose_name_plural = 'Pokoje'

    def __str__(self):
        return f'Pokój nr. {self.room_number}'


class Reservation(models.Model):

    client = models.ForeignKey(Client,
                               related_name='reservations',
                               verbose_name='Klient')

    date_from = models.DateField(verbose_name='Od')

    date_to = models.DateField(verbose_name='Do')

    room = models.ForeignKey(Room,
                             related_name='reservations',
                             verbose_name='Pokój')

    guests_number = models.PositiveIntegerField(verbose_name='Liczba gości')

    breakfast = models.BooleanField(default=False,
                                    verbose_name='Śniadanie')

    additional_info = models.TextField(null=True,
                                       blank=True,
                                       verbose_name='Dodatkowe informacje')

    advance_paid = models.BooleanField(default=False,
                                       verbose_name='Zaliczka opłacona')

    class Meta:
        verbose_name = 'Rezerwacja'
        verbose_name_plural = 'Rezerwacje'
        unique_together = ("date_from", "date_to", "room")

    def __str__(self):
        return f'Rezerwacja na {self.room}  od:{self.date_from} do:{self.date_to}'

    @property
    def total_price(self):
        if self.id:
            if isinstance(self.date_to, str) and isinstance(self.date_from, str):
                date_to = datetime.strptime(self.date_to, '%Y-%m-%d')
                date_from = datetime.strptime(self.date_from, '%Y-%m-%d')

            else:
                date_to = self.date_to
                date_from = self.date_from

            days = (date_to - date_from).days

            return self.guests_number * days * 100
        return ''

    @property
    def advance(self):
        if self.total_price:
            return 0.5 * self.total_price
        return ''

    def get_as_pdf(self):
        year = date.today().year
        line_1 = f'Rezerwacja nr. Z/{self.id}/{year}'
        line_2 = f'{self.client.first_name} {self.client.last_name}'
        line_3 = f'{self.room} Liczba miejsc: {self.guests_number}'
        line_4 = f'OD:  {self.date_from}   DO:  {self.date_to}'
        line_5 = f'Łączna kwota do zapłaty: {self.total_price}'
        line_6 = f'Zaliczka: {self.advance}'
        recipe = [line_1, line_2, line_3, line_4, line_5, line_6]

        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        logo_path = os.path.join(os.path.dirname(root), 'logo_raw_black.png')

        response_pdf = HttpResponse(content_type='application/pdf')
        response_pdf['Content-Disposition'] = 'attachment; filename="reservation.pdf"'

        # Register font with Polish signs
        pdfmetrics.registerFont(TTFont('Arial', 'Arial.ttf'))

        # Create the PDF object, using the response object as its "file."
        pdf = canvas.Canvas(response_pdf, pagesize=A5)
        pdf.setFont('Arial', 12)

        pdf.drawImage(logo_path, 15, 430, width=150, height=150, mask='auto')

        text_pos = 560

        for line in recipe:
            pdf.drawString(190, text_pos, line)
            text_pos -= 15

        pdf.showPage()
        pdf.save()
        return response_pdf


@receiver(signal=models.signals.post_save, sender=Reservation)
def reservation_emails(instance, **kwargs):
    message_admin = f"""
    Otrzymałeś rezerwacje na {instance.room}
    Od {instance.date_from} Do {instance.date_to}
    Dane klienta:
    {instance.client}
    {instance.client.email}
    {instance.client.phone}
    """

    message = 'Szczegóły rezerwacji:'

    send_mail(
        'Otrzymałeś nową rezerwację',
        message_admin,
        'from@example.com',
        ['rafalbielicki@op.pl'],
        fail_silently=False,
    )

    send_mail(
        'Dokonałeś rezerwacji',
        message,
        'from@example.com',
        [instance.client.email],
        fail_silently=False,
    )

zajazd_website/reservation/forms.py
from datetime import date
from django import forms
from .models import Reservation, Room
from django.core.validators import ValidationError
from client.forms import ClientCheckForm


class BaseModelForm(forms.ModelForm):
    def __init__(self, date_from=None, date_to=None,  *args, **kwargs):
        super(BaseModelForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.date_from = date_from
        self.date_to = date_to
        # self.max = max


class BaseReservationForm(BaseModelForm):
    """
    Form contains all Reservation ModelForm custom validations
    """

    def clean(self):
        cleaned_data = super(BaseReservationForm, self).clean()

        if 'date_from' in cleaned_data and 'date_to' in cleaned_data:
            date_from, date_to = cleaned_data['date_from'], cleaned_data['date_to']

            if date_from < date.today():
                raise ValidationError(message='Data przyjazdu nieprawidłowa')

            if date_from > date_to:
                raise ValidationError(message='Data przyjazdu musi być przed datą odjazdu')

            if not Room.objects.available_rooms(cleaned_data['date_from'], cleaned_data['date_to']):
                raise ValidationError(message='Nie ma dostępnego pokoju w danym terminie')

            if date_from == date_to:
                raise ValidationError(message='Minimalna długość pobytu to 1 dzień')

        return cleaned_data


class ReservationFormStep3(BaseReservationForm):
    next_step = ClientCheckForm

    class Meta:
        model = Reservation
        fields = ['guests_number', 'breakfast', 'additional_info']

    def __init__(self, *args, **kwargs):
        super(ReservationFormStep3, self).__init__(*args, **kwargs)
        # if maximum:
        #     self.fields['guests_number'].widget.attrs.update({'max': maximum})


class ReservationFormStep2(BaseReservationForm):
    next_step = ReservationFormStep3

    class Meta:
        model = Reservation
        fields = ['room']

    def __init__(self, *args, **kwargs):
        super(ReservationFormStep2, self).__init__(*args, **kwargs)
        if self.date_from and self.date_to:
            self.fields['room'].queryset = Room.objects.available_rooms(date_from=self.date_from, date_to=self.date_to)


class ReservationFormStep1(BaseReservationForm):
    next_step = ReservationFormStep2

    class Meta:
        model = Reservation
        fields = ['date_from', 'date_to']

    def __init__(self, *args, **kwargs):
        super(ReservationFormStep1, self).__init__(*args, **kwargs)
        self.fields['date_from'].widget.attrs.update({'id': 'from'})
        self.fields['date_to'].widget.attrs.update({'id': 'to'})


class ReservationCreationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['client', 'date_from', 'date_to', 'room', 'guests_number', 'breakfast', 'additional_info']

reservation_form_list = [ReservationFormStep1,
                         ReservationFormStep2,
                         ReservationFormStep3]

zajazd_website/reservation/views.py
from django.shortcuts import render
from django.views import View
from .models import Reservation
from .forms import reservation_form_list, ReservationFormStep1, ReservationCreationForm
from client.forms import client_form_list
from .forms_processing import ReservationFormProcessor
from client.forms_processing import ClientFormProcessor


class ReservationView(View):

    def get(self, request):
        request.session.flush()
        return render(request, 'reservation/reservation_form.html', {'form': ReservationFormStep1()})

    def post(self, request):
        reservation_processor = ReservationFormProcessor(reservation_form_list, request)
        client_processor = ClientFormProcessor(client_form_list, request)

        reservation_processor.form_check()
        if reservation_processor.form:
            form = reservation_processor.process_form()

        client_processor.form_check()
        if client_processor.form:
            form = client_processor.process_form()

        if form:
            return render(request, 'reservation/reservation_form.html', {'form': form})
        else:
            form = ReservationCreationForm(request.session)
            if form.is_valid():
                reservation = form.save()
                request.session['PDF'] = reservation.id
                return render(request, 'reservation/reservation_form.html', {'reservation': reservation})


class Pdf(View):
    def get(self, request):
        reservation = Reservation.objects.get(id=request.session['PDF'])
        return reservation.get_as_pdf()

zajazd_website/reservation/templates/reservation/details.html
{% extends 'base.html' %}
{% block title %}
 - Rezerwacja
{% endblock %}

{% block content %}
<div class="container content-section">
        <div class="col-lg-8 col-lg-offset-2">
<p>
    Rezerwacja nr. Z/{{ reservation.id }}/{{year}} na {{ reservation.client.first_name }} {{ reservation.client.last_name }}<br>
    Nr. Telefonu: {{ reservation.client.phone }}   E-mail: {{ reservation.client.email }}<br>
    OD : {{ reservation.date_from }} DO: {{ reservation.date_to }} <br>
    {{reservation.room }}
    Liczba gości : {{ reservation.guests_number }}
    {% if reservation.breakfast %}
    ze śniadaniem
    {% else %}
    bez śniadania
    {% endif %}<br>
    Dodatkowe informacje: {{ reservation.additional_info }}<br>
    Łączna cena : {{ reservation.total_price }}<br>
    Zaliczka: {{ reservation.advance }}
    <br><br>
    <a href="{% url 'reservation:PDF' %}" class="btn btn-default btn-lg">PDF</a>
    <br><br>
    <a href="{% url 'reservation:reservation' %}" class="btn btn-default btn-lg">Wróć do początku</a>
</p>
        </div>
</div>
{% endblock %}

zajazd_website/reservation/templates/reservation/reservation_form.html
{% extends 'base.html' %}

{% block title %}
 - Rezerwacja
{% endblock %}

{% block content %}
{% if form %}

<div class="container content-section">
    <span class="zajazd-icon logo-white large"></span>
    <h3>Rezerwacje</h3>
    <hr>
    <div class="col-lg-6 col-lg-offset-1">

        <form action="" method="POST">

            {% csrf_token %}
            {{ form }}

            <br>
            <input type="submit" value='Rezerwacja' class="btn btn-default" role="button" >
        </form>
    </div>
</div>

{% endif %}
{% if reservation %}

<div class="container content-section">
     <span class="zajazd-icon logo-white large"></span>
    <h3>Rezerwacje</h3>
    <hr>
    <div class="col-lg-8 col-lg-offset-1">
        <p>
            Rezerwacja nr. Z/{{ reservation.id }}/{{year}} na {{ reservation.client.first_name }} {{ reservation.client.last_name }}<br>
            Nr. Telefonu: {{ reservation.client.phone }}   E-mail: {{ reservation.client.email }}<br>
            OD : {{ reservation.date_from }} DO: {{ reservation.date_to }} <br>
            {{reservation.room }}
            Liczba gości : {{ reservation.guests_number }}
            {% if reservation.breakfast %}
            ze śniadaniem
            {% else %}
            bez śniadania
            {% endif %}<br>
            Dodatkowe informacje: {{ reservation.additional_info }}<br>
            Łączna cena : {{ reservation.total_price }}<br>
            Zaliczka: {{ reservation.advance }}
            <br><br>
            <a href="{% url 'reservation:PDF' %}" class="btn btn-default btn-lg">PDF</a>
            <br><br>
            <a href="{% url 'reservation:reservation' %}" class="btn btn-default btn-lg">Wróć do początku</a>
        </p>
    </div>
</div>

{% endif %}
{% endblock %}