zajazd_website/gallery/urls.py
from django.conf.urls import url
from .views import Albums, Gallery, PhotoView


app_name = 'gallery'

urlpatterns = [
    url(r'^$', Albums.as_view(), name='albums'),
    url(r'^(?P<album_id>(\d)+)/$', Gallery.as_view(), name='photos'),
    url(r'^photo/(?P<photo_id>(\d)+)', PhotoView.as_view(), name='photo')
]

zajazd_website/zajazd_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mainsite.views import Index, AboutUs, Contact
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainsite.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^reservation/', include('reservation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zajazd_website/gallery/models.py
import os
from io import BytesIO

from PIL import Image
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import models
from django.utils.safestring import mark_safe
from django.dispatch import receiver


class Photo(models.Model):
    title = models.CharField(max_length=32,
                             verbose_name='Tytuł')

    image = models.ImageField(upload_to='gallery',
                              null=False,
                              blank=False,
                              verbose_name='Zdjęcie')

    added = models.DateTimeField(auto_now_add=True,
                                 verbose_name='Dodano')

    album = models.ForeignKey('PhotoAlbum',
                              blank=True,
                              null=True,
                              related_name="photos",
                              on_delete=models.SET_NULL)

    thumbnail = models.ImageField(null=True,
                                  upload_to='gallery_thumbnails')

    class Meta:
        verbose_name = 'Zdjęcie'
        verbose_name_plural = 'Zdjęcia'
        ordering = ["-added"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        update = False
        if self.id:
            update = True
        self.create_thumbnail()

        super(Photo, self).save(*args, **kwargs, force_update=update)

    def create_thumbnail(self):

        if not self.image:
            return
        if self.thumbnail:
            return

        img_type = self.image.file.content_type

        if img_type == 'image/jpeg':
            pil_type = 'jpeg'
            extension = 'jpg'
        elif img_type == 'image/png':
            pil_type = 'png'
            extension = 'png'

        image = Image.open(BytesIO(self.image.read()))

        thumb_size = (400, 400)

        image.thumbnail(thumb_size, Image.ANTIALIAS)

        temp = BytesIO()
        image.save(temp, pil_type)
        temp.seek(0)

        thumbnail = SimpleUploadedFile(os.path.split(self.image.name)[-1], temp.read(), content_type=img_type)

        self.thumbnail.save(
            '%s_thumbnail.%s' % (os.path.splitext(thumbnail.name)[0], extension),
            thumbnail,
            save=False
        )


    def admin_image(self):
        return mark_safe(f'<img src="{self.thumbnail.url}"/>')
    admin_image.short_description = 'Zdjęcie'


class PhotoAlbum(models.Model):
    title = models.CharField(max_length=64,
                             verbose_name='Tytuł')

    cover = models.ForeignKey(Photo,
                              null=True,
                              blank=True,
                              on_delete=models.SET_NULL,
                              verbose_name='Okładka')

    description = models.TextField(null=True,
                                   blank=True,
                                   verbose_name='Opis')

    added = models.DateTimeField(auto_now_add=True,
                                 verbose_name="Dodano")

    class Meta:
        verbose_name = 'Album'
        verbose_name_plural = 'Albumy'
        ordering = ["-added"]

    def __str__(self):
        return self.title


@receiver(models.signals.post_delete, sender=Photo)
def delete_images(instance, **kwargs):
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

    if instance.thumbnail:
        if os.path.isfile(instance.thumbnail.path):
            os.remove(instance.thumbnail.path)


@receiver(models.signals.pre_save, sender=Photo)
def delete_changed_image(instance, **kwargs):
    if Photo.objects.filter(id=instance.id).exists():
        old_photo = Photo.objects.get(id=instance.id)
        if instance.image != old_photo.image:
            if os.path.isfile(old_photo.image.path):
                os.remove(old_photo.image.path)

            if os.path.isfile(old_photo.thumbnail.path):
                os.remove(old_photo.thumbnail.path)
            old_photo.thumbnail = None

zajazd_website/gallery/views.py
from django.views.generic import ListView, DetailView
from .models import PhotoAlbum, Photo


class Albums(ListView):
    model = PhotoAlbum
    template_name = 'gallery/albums.html'
    context_object_name = 'albums'


class Gallery(DetailView):
    model = PhotoAlbum
    pk_url_kwarg = 'album_id'
    template_name = 'gallery/gallery.html'
    context_object_name = 'album'


class PhotoView(DetailView):
    model = Photo
    pk_url_kwarg = 'photo_id'
    template_name = 'gallery/photo.html'

zajazd_website/gallery/templates/gallery/albums.html
{% extends 'base.html' %}

{% block title %}
 - Galeria
{% endblock %}

{% block content %}

<div class="container content-section">
    <span class="zajazd-icon logo-white large"></span>
    <h3>Galeria</h3>
    <hr>
    <br><br><br>
    {% for album in albums %}

    <div class="col-lg-4 gallery">
        <a href="{% url 'gallery:photos' album.id %}" title="{{ album.title }}">
            <img src="{{ album.cover.thumbnail.url }}" class="img-thumbnail">
        </a>
    </div>

    {% endfor %}

</div>

{% endblock %}

zajazd_website/gallery/templates/gallery/gallery.html
{% extends 'base.html' %}

{% block title %}
 - Galeria
{% endblock %}

{% block content %}
<div class="container content-section">
    <span class="zajazd-icon logo-white large"></span>
    <h3>Galeria</h3>
    <hr>
    <a href="{% url 'gallery:albums' %}" class="btn btn-default" role="button">Albumy</a>
    <br><br>

    {% for photo in album.photos.all %}

    <div class="col-lg-3 gallery">
        <a href="{% url 'gallery:photo' photo.id %}" title="{{ photo.title }}">
            <img src="{{ photo.thumbnail.url }}" class="img-responsive img-border">
        </a>
    </div>

    {% endfor %}

</div>

{% endblock %}

zajazd_website/gallery/templates/gallery/photo.html
{% extends 'base.html' %}

{% block title %}
 - Galeria
{% endblock %}

{% block content %}

<div class="container content-section">
    <span class="zajazd-icon logo-white large"></span>
    <h3>Galeria</h3>
    <hr>
    <a href="{% url 'gallery:photos' photo.album.id %}" class="btn btn-default" role="button">Album</a>
    <br><br><br>
    <img src="{{ photo.image.url }}" class="img-responsive center-block">
</div>

{% endblock %}